### ISSUE TITLE
Question about iterative training 

### ISSUE THREAD

**Issue by PKUTAN** [TheLuoFengLab/DDDM#1]
<img width="279" alt="截屏2024-08-05 12 17 24" src="https://github.com/user-attachments/assets/24118617-411b-42c2-9a38-54ef1f3367f3">

The condition term for Unet input is actually x_0 rather than the predicted x_0 by Unet?

This seems not align with your paper?

**Comment by Snowman-of-Fire** [comment]
I would like to second this. Your implementation appears to be different from what is mentioned in the paper unless I am misunderstanding something.

**Comment by zhangdan8962** [comment]
Please see this line https://github.com/TheLuoFengLab/DDDM/blob/7af706893fa63d1040f81461febaf13178615c7f/DDDM/train_util.py#L194

**Comment by Snowman-of-Fire** [comment]
However, you do not save the output from the model. Instead, you update it with the previous iteration's noised version of the image.

https://github.com/TheLuoFengLab/DDDM/blob/7af706893fa63d1040f81461febaf13178615c7f/DDDM/train_util.py#L216
